# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [1]:
# Import Pandas library
import pandas as pd

In [5]:
# Load data list from url
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
insurance_df = pd.read_csv(url)

In [7]:
insurance_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
type(insurance_df)

pandas.core.frame.DataFrame

In [19]:
# Identify the dimensions of the dataset by determining the number of rows, columns it contains.
insurance_df.shape

(4008, 11)

In [33]:
# Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable.
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [39]:
insurance_df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [41]:
# The columns "Income", "Monthly Premium Auto" and "Total Claim Amount" contain floats, i.e. numerical values.
# All other columns contains strings, i.e. categorical values.
# You should also provide suggestions for fixing any incorrect data types!
# Customer Lifetime Value could be turned into an integer ?

In [35]:
# Identify the number of unique values for each column and determine which columns appear to be categorical. 
# You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.

insurance_df.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [53]:
insurance_df["ST"].unique() # State is categorical, but there is abbreviations and full names present!

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [81]:
insurance_df["ST"].value_counts() # WA needs to be added to Washington. AZ needs to be added to Arizona.

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [59]:
insurance_df["GENDER"].unique() # Gender is categorical, but there is 5 instead of 2 categories !

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [85]:
insurance_df["GENDER"].value_counts() # Male needs to be added to M, female and Femal need to be added to F.

GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [91]:
insurance_df["Education"].unique() # Education is categorical with 5 different categories. Sadly, Bachelor & Bachelors are two different values for the same category.

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [95]:
insurance_df["Education"].value_counts() # Most customers have a bachelor degree. Bachelor & Bachelors need to be summed up.

Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

In [101]:
insurance_df["Number of Open Complaints"].unique() # Open Complaints is categorical with 6 different categories.

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [103]:
insurance_df["Number of Open Complaints"].value_counts()

Number of Open Complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64

In [105]:
insurance_df["Policy Type"].unique() # Policy Type is nicely categorical with 3 different categories.

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

In [109]:
insurance_df["Policy Type"].value_counts() # Most customers have a Personal Auto insured.

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [111]:
insurance_df["Vehicle Class"].unique() # Vehicle Class is nicely categorical with 6 different categories.

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [115]:
insurance_df["Vehicle Class"].value_counts() # Most customers have a 4-door car.

Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [121]:
insurance_df["Income"].max() # Maximum of income (numerical value).

99960.0

In [123]:
insurance_df["Income"].min() # Minimum of income (numerical value).

0.0

In [127]:
insurance_df["Monthly Premium Auto"].max() # Maximum of Monthly Premium Auto (numerical value).

35354.0

In [129]:
insurance_df["Monthly Premium Auto"].min() # Minimum of Monthly Premium Auto (numerical value).

61.0

In [133]:
insurance_df["Total Claim Amount"].max() # Maximum of Total Claim Amount (numerical value).

2893.239678

In [135]:
insurance_df["Total Claim Amount"].min() # Minimum of Total Claim Amount (numerical value).

0.382107

In [139]:
# Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency
# and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
insurance_df.describe()

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [143]:
# Compute summary statistics for categorical columns and providing your conclusions based on these statistics.
# See above comments.

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [149]:
# Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.
state_df = insurance_df[["ST"]]

In [151]:
state_df

              ST
0     Washington
1        Arizona
2         Nevada
3     California
4     Washington
...          ...
4003         NaN
4004         NaN
4005         NaN
4006         NaN
4007         NaN

[4008 rows x 1 columns]

In [161]:
state_df["ST"].value_counts() # The 5 less common locations are Nevada < (Washington+WA) < (Arizona+AZ) < Oregon < (California+Cali)

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [163]:
state_df["ST"].sort_values(ascending=False)

0       Washington
884     Washington
163     Washington
914     Washington
897     Washington
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: ST, Length: 4008, dtype: object

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [165]:
# Create a pandas Series object that contains the policy types and their total number of policies sold, 
# and then retrieve the policy type with the highest number of policies sold.
policies_df = insurance_df[["Policy Type"]]

In [215]:
policies_df["Policy Type"].value_counts() # Most customers have a Personal Auto insured.

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [213]:
policies_df["Policy Type"].value_counts().max()

780

In [219]:
print(policies_df["Policy Type"].value_counts().index[0])
print(policies_df["Policy Type"].value_counts()[0])

Personal Auto
780

C:\Users\admin\AppData\Local\Temp\ipykernel_16232\4147057224.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(policies_df["Policy Type"].value_counts()[0])

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [191]:
# The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. 
# How does the average income compare between the two policy types?
type_income_df = insurance_df[["Policy Type", "Income"]]

In [193]:
type_income_df

         Policy Type   Income
0      Personal Auto      0.0
1      Personal Auto      0.0
2      Personal Auto  48767.0
3     Corporate Auto      0.0
4      Personal Auto  36357.0
...              ...      ...
4003             NaN      NaN
4004             NaN      NaN
4005             NaN      NaN
4006             NaN      NaN
4007             NaN      NaN

[4008 rows x 2 columns]

In [235]:
# Calculate the average income for Personal Auto and Corporate Auto 
print("The mean income of customers with a personal auto is:")
type_income_df.loc[type_income_df["Policy Type"]=="Personal Auto"]["Income"].mean()

The mean income of customers with a personal auto is:

38180.69871794872

In [237]:
print("The mean income of customers with a corporate auto is:")
type_income_df.loc[type_income_df["Policy Type"]=="Corporate Auto"]["Income"].mean()

The mean income of customers with a corporate auto is:

41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here